language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
      osx_image: xcode9.2

before_install:
  - ./.travis/install.sh

script:
  - ./.travis/build.sh
