language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.2

before_install:
  - ./.travis/install.sh
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export PATH="/usr/local/opt/bison/bin:/usr/local/bin:$PATH"; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export DEPS_SOURCE=`pwd`/macos; fi

script:
  - ./.travis/build.sh
