# Azure build pipeline script
# Add steps that build, run tests, deploy, and more: https://aka.ms/yaml

resources:
  containers:
  - container: LinuxContainer
    image: ubuntu:16.04

jobs:
- job: LuxCoreRenderLinux
  pool:
    vmImage: 'ubuntu-16.04'

  container: LinuxContainer

  steps:
  - script: |
      sudo apt-get -qq update && sudo apt-get install -y git cmake g++ flex bison libbz2-dev libopenimageio-dev libtiff5-dev libpng12-dev libgtk-3-dev libopenexr-dev libgl1-mesa-dev python3-dev python3-pip python3-numpy
      ./scripts/azurepipeline/build.sh
    displayName: Building LuxCore
 
