# Azure build pipeline script
# Add steps that build, run tests, deploy, and more: https://aka.ms/yaml

jobs:
    - job: Linux
		pool:
			vmImage: 'Ubuntu 16.04'

		steps:
		- script: ./scripts/build.sh
			displayName: Building LuxCore
