# Azure build pipeline script
# Add steps that build, run tests, deploy, and more: https://aka.ms/yaml

resources:
  containers:
  - container: LinuxContainer
    image: ubuntu:16.04

jobs:
- job: Building LuxCoreRender on Linux
  pool:
    vmImage: 'ubuntu-16.04'

  container: LinuxContainer

  steps:
  - script: ./scripts/azurepipeline/build.sh
    displayName: Building LuxCore
 
