# Azure build pipeline script
# Add steps that build, run tests, deploy, and more: https://aka.ms/yaml

resources:
  containers:
  - container: LinuxContainer
    image: ubuntu:14.04

jobs:
- job: LuxCoreRenderLinux
  pool:
    vmImage: 'ubuntu-16.04'

  container: LinuxContainer

  steps:
#  - script: ./scripts/azurepipeline/build.sh
#    displayName: Building LuxCore
#  - script: ./scripts/azurepipeline/test.sh
#    displayName: Testing LuxCore
  - task: PublishBuildArtifacts@1
    inputs:
#      pathtoPublish: '$(System.DefaultWorkingDirectory)/LinuxCompile/target-64-sse2/LuxCore.tar.bz2'
      pathtoPublish: '$(System.DefaultWorkingDirectory)/README.md'
      artifactName: README
    displayName: 'Upload README'
    condition: eq(variables['System.PullRequest.IsFork'], 'False')
